### ISSUE TITLE
Vyper contract bindings

### ISSUE THREAD

**Issue by 0xEstelle** [primitivefinance/arbiter#222]
The need arose when investigating importing Curve contracts into the environment (Curve is written in Vyper). This issue is necessary to resolve issue #221.

**Comment by 0xJepsen** [comment]
Hey @0xEstelle! I think we can generate bindings for curve contracts now problem. I think the steps for this will first be to 
- [ ] install the curve repository as a git submodule with forge. Documentation on this can be found [here](https://book.getfoundry.sh/projects/dependencies?highlight=submo#dependencies). Let me know if you need help with this, I know the submodules can be kinda a pain to work with. It's important to only be using forge to do this and not git. 
- [ ] Then modify the `./bind` shell script here https://github.com/primitivefinance/arbiter/blob/329a18c2b41365edeb6e37b32e7eca1a2d267073/bind.sh#L5-L14 by adding another line to generate the bindings for the vyper contracts. Try running the shell script after changes are made and If this doesn't work we may need to dive a little deeper. If this does go well then we should have the bindings in our crate should be able to use them appropriately.


It is my suspicion that this should work since the bind command generates them from the abi we get from compiling the contracts. Worst case we may need to look into a vyper compiler package.

**Comment by Autoparallel** [comment]
> Hey @0xEstelle! I think we can generate bindings for curve contracts now problem. I think the steps for this will first be to
> 
> * [ ]  install the curve repository as a git submodule with forge. Documentation on this can be found [here](https://book.getfoundry.sh/projects/dependencies?highlight=submo#dependencies). Let me know if you need help with this, I know the submodules can be kinda a pain to work with. It's important to only be using forge to do this and not git.
> * [ ]  Then modify the `./bind` shell script here https://github.com/primitivefinance/arbiter/blob/329a18c2b41365edeb6e37b32e7eca1a2d267073/bind.sh#L5-L14
>    by adding another line to generate the bindings for the vyper contracts. Try running the shell script after changes are made and If this doesn't work we may need to dive a little deeper. If this does go well then we should have the bindings in our crate should be able to use them appropriately.
> 
> It is my suspicion that this should work since the bind command generates them from the abi we get from compiling the contracts. Worst case we may need to look into a vyper compiler package.

I don't think Forge will work with non-solidity contracts out of the box!
