### ISSUE TITLE
allow the user to have a custom config filepath

### ISSUE THREAD

**Issue by ts0yu** [primitivefinance/arbiter#48]
we should make it so that a user can run `arbiter see --config <name>.toml` instead of only having predefined paths. it should still be able to accept `arbiter see --config`

**Comment by 0xJepsen** [comment]
in `arbiter/crates/cli/src/config/mod.rs` you will see this is where we parse the config file. If you run `arbiter see --config` right now it will iterate through the specified file paths of "where to look" for a file called either Config.toml or config.toml. So in the current implementation there is a specific place where the user must put their config file and it must have a specific name. thus the `--config` flag represents a boolean value that the program just checks is present. What we would like to do is all a user to "optionally" (use option type for the subcommand) specify a file name and path after the `--config` flag such that command would look something like this: arbiter see `---config somefilepathandname.toml` so that the user can specify where their config file is and what it is called. Everything for this issue is in the cli crate.

**Comment by eljhfx** [comment]
Mind assigning me to this one?

**Comment by Autoparallel** [comment]
@eljhfx on it.

**Comment by eljhfx** [comment]
PR: #69
