### ISSUE TITLE
refactor: make Manager simpler

### ISSUE THREAD

**Issue by zeroXbrock** [primitivefinance/arbiter#512]
# Idea

Make manager return references to things instead of requiring users to name everything and look it up themselves.

How it is:

```rs
let mut manager = Manager::new();
let params = EnvironmentParameters {
    label: ENV_LABEL.to_string(),
    block_settings: BlockSettings::UserControlled,
    gas_settings: GasSettings::UserControlled,
};
manager.add_environment(params)?;
manager.start_environment(ENV_LABEL)?;
```

How I think it should be:

```rs
let mut manager = Manager::new();
let params = EnvironmentParameters {
    block_settings: BlockSettings::UserControlled,
    gas_settings: GasSettings::UserControlled,
};
let env = manager.add_environment(params)?;
env.start()?;
```

## Solution

- remove `label` entirely
- refactor return value of `add_environment` to return a reference to the environment
- add `start` function to said environment

**Comment by kinrezC** [comment]
I like this approach, but to take it a step further we'd probably want to do away with `manager` altogether since its sole purpose is to contain a map of environments.  Much of the rationale for labels was re: postprocessing/tagging of datasets but arbiter doesn't need to be opinionated about that.

New api could look like:
```rust
let params = EnvironmentParameters {
    block_settings: BlockSettings::UserControlled,
    gas_settings: GasSettings::UserControlled,
};
let env = Environment::new(params)?;
env.start()?;
```

Would also be nice to introduce a default implementation for `EnvironmentParameters` to simplify it further.

**Comment by zeroXbrock** [comment]
💯 $\cdot$ 💯 totally agree. if the manager's only job is to map environments, it seems a bit redundant & like you said, opinionated

**Comment by Autoparallel** [comment]
I don't think removing the label entirely is a good idea all though the rest seems good. 

Labels are useful when outputting data and should be optional. You may want to know that a specific environment bugged out and without labels, you'd just have to add labels yourself.
